# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 684)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(130, 30, 861, 591))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_timer = QtWidgets.QWidget()
        self.tab_timer.setObjectName("tab_timer")
        self.groupBox = QtWidgets.QGroupBox(self.tab_timer)
        self.groupBox.setGeometry(QtCore.QRect(30, 30, 291, 241))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 40, 226, 181))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.Grid_micro_break = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.Grid_micro_break.setContentsMargins(0, 0, 0, 0)
        self.Grid_micro_break.setObjectName("Grid_micro_break")
        self.work_s_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.work_s_mic.setMaximum(59)
        self.work_s_mic.setObjectName("work_s_mic")
        self.Grid_micro_break.addWidget(self.work_s_mic, 0, 3, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.Grid_micro_break.addWidget(self.label_2, 1, 0, 1, 1)
        self.post_m_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.post_m_mic.setMaximum(59)
        self.post_m_mic.setObjectName("post_m_mic")
        self.Grid_micro_break.addWidget(self.post_m_mic, 2, 2, 1, 1)
        self.break_s_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.break_s_mic.setMaximum(59)
        self.break_s_mic.setProperty("value", 16)
        self.break_s_mic.setObjectName("break_s_mic")
        self.Grid_micro_break.addWidget(self.break_s_mic, 1, 3, 1, 1)
        self.post_h_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.post_h_mic.setObjectName("post_h_mic")
        self.Grid_micro_break.addWidget(self.post_h_mic, 2, 1, 1, 1)
        self.work_m_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.work_m_mic.setMaximum(59)
        self.work_m_mic.setObjectName("work_m_mic")
        self.Grid_micro_break.addWidget(self.work_m_mic, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.Grid_micro_break.addWidget(self.label, 0, 0, 1, 1)
        self.post_s_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.post_s_mic.setMaximum(59)
        self.post_s_mic.setObjectName("post_s_mic")
        self.Grid_micro_break.addWidget(self.post_s_mic, 2, 3, 1, 1)
        self.break_m_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.break_m_mic.setMaximum(59)
        self.break_m_mic.setObjectName("break_m_mic")
        self.Grid_micro_break.addWidget(self.break_m_mic, 1, 2, 1, 1)
        self.work_h_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.work_h_mic.setObjectName("work_h_mic")
        self.Grid_micro_break.addWidget(self.work_h_mic, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.Grid_micro_break.addWidget(self.label_3, 2, 0, 1, 1)
        self.break_h_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.break_h_mic.setObjectName("break_h_mic")
        self.Grid_micro_break.addWidget(self.break_h_mic, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.Grid_micro_break.addWidget(self.label_4, 3, 0, 1, 1)
        self.idle_h_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.idle_h_mic.setObjectName("idle_h_mic")
        self.Grid_micro_break.addWidget(self.idle_h_mic, 3, 1, 1, 1)
        self.idle_m_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.idle_m_mic.setMaximum(59)
        self.idle_m_mic.setObjectName("idle_m_mic")
        self.Grid_micro_break.addWidget(self.idle_m_mic, 3, 2, 1, 1)
        self.idle_s_mic = QtWidgets.QSpinBox(self.gridLayoutWidget)
        self.idle_s_mic.setMaximum(59)
        self.idle_s_mic.setObjectName("idle_s_mic")
        self.Grid_micro_break.addWidget(self.idle_s_mic, 3, 3, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_timer)
        self.groupBox_2.setGeometry(QtCore.QRect(350, 30, 291, 241))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(20, 40, 226, 181))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.Grid_micro_break_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.Grid_micro_break_3.setContentsMargins(0, 0, 0, 0)
        self.Grid_micro_break_3.setObjectName("Grid_micro_break_3")
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_15.setObjectName("label_15")
        self.Grid_micro_break_3.addWidget(self.label_15, 3, 0, 1, 1)
        self.idle_m_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.idle_m_mac.setMaximum(59)
        self.idle_m_mac.setObjectName("idle_m_mac")
        self.Grid_micro_break_3.addWidget(self.idle_m_mac, 3, 2, 1, 1)
        self.idle_h_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.idle_h_mac.setObjectName("idle_h_mac")
        self.Grid_micro_break_3.addWidget(self.idle_h_mac, 3, 1, 1, 1)
        self.work_m_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.work_m_mac.setMaximum(59)
        self.work_m_mac.setObjectName("work_m_mac")
        self.Grid_micro_break_3.addWidget(self.work_m_mac, 0, 2, 1, 1)
        self.work_s_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.work_s_mac.setMaximum(59)
        self.work_s_mac.setObjectName("work_s_mac")
        self.Grid_micro_break_3.addWidget(self.work_s_mac, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.Grid_micro_break_3.addWidget(self.label_8, 0, 0, 1, 1)
        self.break_h_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.break_h_mac.setObjectName("break_h_mac")
        self.Grid_micro_break_3.addWidget(self.break_h_mac, 1, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.Grid_micro_break_3.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_9.setObjectName("label_9")
        self.Grid_micro_break_3.addWidget(self.label_9, 2, 0, 1, 1)
        self.work_h_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.work_h_mac.setObjectName("work_h_mac")
        self.Grid_micro_break_3.addWidget(self.work_h_mac, 0, 1, 1, 1)
        self.post_s_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.post_s_mac.setMaximum(59)
        self.post_s_mac.setObjectName("post_s_mac")
        self.Grid_micro_break_3.addWidget(self.post_s_mac, 2, 3, 1, 1)
        self.break_s_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.break_s_mac.setMaximum(59)
        self.break_s_mac.setObjectName("break_s_mac")
        self.Grid_micro_break_3.addWidget(self.break_s_mac, 1, 3, 1, 1)
        self.post_m_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.post_m_mac.setMaximum(59)
        self.post_m_mac.setObjectName("post_m_mac")
        self.Grid_micro_break_3.addWidget(self.post_m_mac, 2, 2, 1, 1)
        self.post_h_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.post_h_mac.setObjectName("post_h_mac")
        self.Grid_micro_break_3.addWidget(self.post_h_mac, 2, 1, 1, 1)
        self.break_m_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.break_m_mac.setMaximum(59)
        self.break_m_mac.setObjectName("break_m_mac")
        self.Grid_micro_break_3.addWidget(self.break_m_mac, 1, 2, 1, 1)
        self.idle_s_mac = QtWidgets.QSpinBox(self.gridLayoutWidget_2)
        self.idle_s_mac.setMaximum(59)
        self.idle_s_mac.setObjectName("idle_s_mac")
        self.Grid_micro_break_3.addWidget(self.idle_s_mac, 3, 3, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_timer)
        self.groupBox_3.setGeometry(QtCore.QRect(50, 320, 171, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.widget = QtWidgets.QWidget(self.groupBox_3)
        self.widget.setGeometry(QtCore.QRect(20, 30, 115, 76))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.show_timer_cbox = QtWidgets.QCheckBox(self.widget)
        self.show_timer_cbox.setObjectName("show_timer_cbox")
        self.verticalLayout.addWidget(self.show_timer_cbox)
        self.show_skip_cbox = QtWidgets.QCheckBox(self.widget)
        self.show_skip_cbox.setObjectName("show_skip_cbox")
        self.verticalLayout.addWidget(self.show_skip_cbox)
        self.show_post_cbox = QtWidgets.QCheckBox(self.widget)
        self.show_post_cbox.setObjectName("show_post_cbox")
        self.verticalLayout.addWidget(self.show_post_cbox)
        self.start_push = QtWidgets.QPushButton(self.tab_timer)
        self.start_push.setGeometry(QtCore.QRect(270, 340, 93, 28))
        self.start_push.setObjectName("start_push")
        self.get_value_push = QtWidgets.QPushButton(self.tab_timer)
        self.get_value_push.setGeometry(QtCore.QRect(400, 340, 93, 28))
        self.get_value_push.setObjectName("get_value_push")
        self.save_push = QtWidgets.QPushButton(self.tab_timer)
        self.save_push.setGeometry(QtCore.QRect(400, 390, 93, 28))
        self.save_push.setObjectName("save_push")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_timer)
        self.groupBox_7.setGeometry(QtCore.QRect(660, 30, 161, 91))
        self.groupBox_7.setObjectName("groupBox_7")
        self.total_time = QtWidgets.QTimeEdit(self.groupBox_7)
        self.total_time.setGeometry(QtCore.QRect(10, 30, 118, 22))
        self.total_time.setTime(QtCore.QTime(10, 0, 0))
        self.total_time.setObjectName("total_time")
        self.tabWidget.addTab(self.tab_timer, "")
        self.tab_camera = QtWidgets.QWidget()
        self.tab_camera.setObjectName("tab_camera")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_camera)
        self.groupBox_4.setGeometry(QtCore.QRect(70, 70, 291, 241))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_4)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(20, 40, 235, 181))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.Grid_micro_break_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.Grid_micro_break_2.setContentsMargins(0, 0, 0, 0)
        self.Grid_micro_break_2.setObjectName("Grid_micro_break_2")
        self.sample_period_m = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sample_period_m.setMaximum(59)
        self.sample_period_m.setObjectName("sample_period_m")
        self.Grid_micro_break_2.addWidget(self.sample_period_m, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName("label_5")
        self.Grid_micro_break_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.label_6.setObjectName("label_6")
        self.Grid_micro_break_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.sample_period_h = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sample_period_h.setObjectName("sample_period_h")
        self.Grid_micro_break_2.addWidget(self.sample_period_h, 0, 1, 1, 1)
        self.sample_duration_m = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sample_duration_m.setMaximum(59)
        self.sample_duration_m.setObjectName("sample_duration_m")
        self.Grid_micro_break_2.addWidget(self.sample_duration_m, 1, 2, 1, 1)
        self.sample_period_s = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sample_period_s.setMaximum(59)
        self.sample_period_s.setObjectName("sample_period_s")
        self.Grid_micro_break_2.addWidget(self.sample_period_s, 0, 3, 1, 1)
        self.sample_duration_s = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sample_duration_s.setMaximum(59)
        self.sample_duration_s.setObjectName("sample_duration_s")
        self.Grid_micro_break_2.addWidget(self.sample_duration_s, 1, 3, 1, 1)
        self.sample_duration_h = QtWidgets.QSpinBox(self.gridLayoutWidget_3)
        self.sample_duration_h.setObjectName("sample_duration_h")
        self.Grid_micro_break_2.addWidget(self.sample_duration_h, 1, 1, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_camera)
        self.groupBox_5.setGeometry(QtCore.QRect(390, 70, 371, 241))
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_5)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(20, 30, 345, 181))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.Grid_micro_break_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.Grid_micro_break_4.setContentsMargins(0, 0, 0, 0)
        self.Grid_micro_break_4.setObjectName("Grid_micro_break_4")
        self.rbut_cf = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.rbut_cf.setObjectName("rbut_cf")
        self.Grid_micro_break_4.addWidget(self.rbut_cf, 0, 2, 1, 1)
        self.param_box_tf = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.param_box_tf.setMaximum(1.0)
        self.param_box_tf.setSingleStep(0.1)
        self.param_box_tf.setObjectName("param_box_tf")
        self.Grid_micro_break_4.addWidget(self.param_box_tf, 1, 1, 1, 1)
        self.post_m_mic_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.post_m_mic_3.setMaximum(1)
        self.post_m_mic_3.setObjectName("post_m_mic_3")
        self.Grid_micro_break_4.addWidget(self.post_m_mic_3, 1, 2, 1, 1)
        self.post_s_mic_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_4)
        self.post_s_mic_3.setObjectName("post_s_mic_3")
        self.Grid_micro_break_4.addWidget(self.post_s_mic_3, 1, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.Grid_micro_break_4.addWidget(self.label_11, 1, 0, 1, 1)
        self.rbut_tf = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.rbut_tf.setObjectName("rbut_tf")
        self.Grid_micro_break_4.addWidget(self.rbut_tf, 0, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_10.setObjectName("label_10")
        self.Grid_micro_break_4.addWidget(self.label_10, 0, 0, 1, 1)
        self.rbut_haar = QtWidgets.QRadioButton(self.gridLayoutWidget_4)
        self.rbut_haar.setObjectName("rbut_haar")
        self.Grid_micro_break_4.addWidget(self.rbut_haar, 0, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.Grid_micro_break_4.addWidget(self.label_12, 2, 0, 1, 1)
        self.img_resize_box = QtWidgets.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.img_resize_box.setMaximum(1.0)
        self.img_resize_box.setSingleStep(0.1)
        self.img_resize_box.setObjectName("img_resize_box")
        self.Grid_micro_break_4.addWidget(self.img_resize_box, 2, 1, 1, 1)
        self.take_pic_push = QtWidgets.QPushButton(self.tab_camera)
        self.take_pic_push.setEnabled(False)
        self.take_pic_push.setGeometry(QtCore.QRect(80, 340, 93, 28))
        self.take_pic_push.setObjectName("take_pic_push")
        self.save_pic_push = QtWidgets.QPushButton(self.tab_camera)
        self.save_pic_push.setEnabled(False)
        self.save_pic_push.setGeometry(QtCore.QRect(80, 410, 93, 28))
        self.save_pic_push.setCheckable(False)
        self.save_pic_push.setObjectName("save_pic_push")
        self.take_vid_push = QtWidgets.QPushButton(self.tab_camera)
        self.take_vid_push.setEnabled(False)
        self.take_vid_push.setGeometry(QtCore.QRect(190, 340, 93, 28))
        self.take_vid_push.setObjectName("take_vid_push")
        self.save_vid_push = QtWidgets.QPushButton(self.tab_camera)
        self.save_vid_push.setEnabled(False)
        self.save_vid_push.setGeometry(QtCore.QRect(190, 410, 93, 28))
        self.save_vid_push.setObjectName("save_vid_push")
        self.vid_view = QtWidgets.QLabel(self.tab_camera)
        self.vid_view.setGeometry(QtCore.QRect(410, 330, 291, 181))
        self.vid_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vid_view.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.vid_view.setText("")
        self.vid_view.setObjectName("vid_view")
        self.det_check = QtWidgets.QCheckBox(self.tab_camera)
        self.det_check.setGeometry(QtCore.QRect(300, 400, 81, 20))
        self.det_check.setChecked(True)
        self.det_check.setObjectName("det_check")
        self.test_cam_check = QtWidgets.QCheckBox(self.tab_camera)
        self.test_cam_check.setEnabled(True)
        self.test_cam_check.setGeometry(QtCore.QRect(300, 350, 81, 20))
        self.test_cam_check.setChecked(False)
        self.test_cam_check.setObjectName("test_cam_check")
        self.tabWidget.addTab(self.tab_camera, "")
        self.tab_misc = QtWidgets.QWidget()
        self.tab_misc.setObjectName("tab_misc")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_misc)
        self.groupBox_6.setGeometry(QtCore.QRect(170, 90, 291, 241))
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_6)
        self.gridLayoutWidget_5.setGeometry(QtCore.QRect(20, 40, 235, 181))
        self.gridLayoutWidget_5.setObjectName("gridLayoutWidget_5")
        self.Grid_micro_break_5 = QtWidgets.QGridLayout(self.gridLayoutWidget_5)
        self.Grid_micro_break_5.setContentsMargins(0, 0, 0, 0)
        self.Grid_micro_break_5.setObjectName("Grid_micro_break_5")
        self.work_m_mic_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.work_m_mic_3.setObjectName("work_m_mic_3")
        self.Grid_micro_break_5.addWidget(self.work_m_mic_3, 0, 2, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_13.setObjectName("label_13")
        self.Grid_micro_break_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget_5)
        self.label_14.setObjectName("label_14")
        self.Grid_micro_break_5.addWidget(self.label_14, 1, 0, 1, 1)
        self.work_h_mic_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.work_h_mic_3.setObjectName("work_h_mic_3")
        self.Grid_micro_break_5.addWidget(self.work_h_mic_3, 0, 1, 1, 1)
        self.post_m_mic_4 = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.post_m_mic_4.setObjectName("post_m_mic_4")
        self.Grid_micro_break_5.addWidget(self.post_m_mic_4, 1, 2, 1, 1)
        self.work_s_mic_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.work_s_mic_3.setObjectName("work_s_mic_3")
        self.Grid_micro_break_5.addWidget(self.work_s_mic_3, 0, 3, 1, 1)
        self.post_s_mic_4 = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.post_s_mic_4.setObjectName("post_s_mic_4")
        self.Grid_micro_break_5.addWidget(self.post_s_mic_4, 1, 3, 1, 1)
        self.post_h_mic_3 = QtWidgets.QSpinBox(self.gridLayoutWidget_5)
        self.post_h_mic_3.setObjectName("post_h_mic_3")
        self.Grid_micro_break_5.addWidget(self.post_h_mic_3, 1, 1, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.tab_misc)
        self.lcdNumber.setGeometry(QtCore.QRect(150, 340, 64, 23))
        self.lcdNumber.setSmallDecimalPoint(True)
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(self.tab_misc)
        self.lcdNumber_2.setGeometry(QtCore.QRect(230, 340, 64, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(self.tab_misc)
        self.lcdNumber_3.setGeometry(QtCore.QRect(310, 340, 64, 23))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.progressBar = QtWidgets.QProgressBar(self.tab_misc)
        self.progressBar.setEnabled(True)
        self.progressBar.setGeometry(QtCore.QRect(230, 400, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.tabWidget.addTab(self.tab_misc, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tab_timer.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "Micro Break"))
        self.label_2.setText(_translate("MainWindow", "break duration"))
        self.label.setText(_translate("MainWindow", "work duration"))
        self.label_3.setText(_translate("MainWindow", "postpone time"))
        self.label_4.setText(_translate("MainWindow", "idle time"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Macro Break"))
        self.label_15.setText(_translate("MainWindow", "idle time"))
        self.label_8.setText(_translate("MainWindow", "work duration"))
        self.label_7.setText(_translate("MainWindow", "break duration"))
        self.label_9.setText(_translate("MainWindow", "postpone time"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Options"))
        self.show_timer_cbox.setText(_translate("MainWindow", "show timer"))
        self.show_skip_cbox.setText(_translate("MainWindow", "show skip"))
        self.show_post_cbox.setText(_translate("MainWindow", "show postpone"))
        self.start_push.setText(_translate("MainWindow", "start"))
        self.get_value_push.setText(_translate("MainWindow", "get values"))
        self.save_push.setText(_translate("MainWindow", "save values"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Total daily"))
        self.total_time.setDisplayFormat(_translate("MainWindow", "h:mm "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_timer), _translate("MainWindow", "timer"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Sampling"))
        self.label_5.setText(_translate("MainWindow", "sample period"))
        self.label_6.setText(_translate("MainWindow", "sample duration"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Algorithm"))
        self.rbut_cf.setText(_translate("MainWindow", "caffe"))
        self.label_11.setText(_translate("MainWindow", "parameter"))
        self.rbut_tf.setText(_translate("MainWindow", "tensorflow"))
        self.label_10.setText(_translate("MainWindow", "Algorithm"))
        self.rbut_haar.setText(_translate("MainWindow", "haaris"))
        self.label_12.setText(_translate("MainWindow", "image"))
        self.take_pic_push.setText(_translate("MainWindow", "take a picture"))
        self.save_pic_push.setText(_translate("MainWindow", "save picture"))
        self.take_vid_push.setText(_translate("MainWindow", "take a vid"))
        self.save_vid_push.setText(_translate("MainWindow", "save vid"))
        self.det_check.setText(_translate("MainWindow", "detect"))
        self.test_cam_check.setText(_translate("MainWindow", "test cam"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_camera), _translate("MainWindow", "camera"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Sampling"))
        self.label_13.setText(_translate("MainWindow", "sample period"))
        self.label_14.setText(_translate("MainWindow", "sample duration"))
        self.progressBar.setFormat(_translate("MainWindow", "%p%"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_misc), _translate("MainWindow", "misc"))

